#!/bin/bash
# Auto-setup script for Dev Containers with Claude Code OAuth token
# This script configures your development environment with CLAUDE_CODE_OAUTH_TOKEN

set -e

echo "🔧 Claude Quickstarts - Dev Container OAuth Setup"
echo "=================================================="
echo ""

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Function to print colored messages
print_success() {
    echo -e "${GREEN}✓${NC} $1"
}

print_info() {
    echo -e "${BLUE}ℹ${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

print_error() {
    echo -e "${RED}✗${NC} $1"
}

# Check if CLAUDE_CODE_OAUTH_TOKEN is set
if [ -z "$CLAUDE_CODE_OAUTH_TOKEN" ]; then
    print_error "CLAUDE_CODE_OAUTH_TOKEN is not set"
    echo ""
    echo "Please set the CLAUDE_CODE_OAUTH_TOKEN environment variable first:"
    echo ""
    echo "  export CLAUDE_CODE_OAUTH_TOKEN=\"your-token-here\""
    echo ""
    echo "Or add it to your shell profile (~/.bashrc, ~/.zshrc, etc.)"
    exit 1
fi

print_success "CLAUDE_CODE_OAUTH_TOKEN is set"

# Check if ANTHROPIC_API_KEY is set
if [ -z "$ANTHROPIC_API_KEY" ]; then
    print_warning "ANTHROPIC_API_KEY is not set"
    echo ""
    read -p "Do you want to set it now? (y/n) " -n 1 -r
    echo ""
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        read -p "Enter your Anthropic API key: " ANTHROPIC_API_KEY
        export ANTHROPIC_API_KEY
        print_success "ANTHROPIC_API_KEY set for this session"
        echo ""
        echo "To make it permanent, add this to your shell profile:"
        echo "  export ANTHROPIC_API_KEY=\"$ANTHROPIC_API_KEY\""
        echo ""
    fi
else
    print_success "ANTHROPIC_API_KEY is set"
fi

# Detect the project directory
PROJECT_DIR="."
if [ -f "package.json" ]; then
    PROJECT_NAME=$(basename "$PWD")
    print_info "Detected project: $PROJECT_NAME"
elif [ -d "customer-support-agent" ] || [ -d "financial-data-analyst" ] || [ -d "computer-use-demo" ]; then
    print_info "Detected claude-quickstarts root directory"
    echo ""
    echo "Available projects:"
    echo "  1) customer-support-agent"
    echo "  2) financial-data-analyst"
    echo "  3) computer-use-demo"
    echo "  4) All projects"
    echo ""
    read -p "Select a project (1-4): " -n 1 -r
    echo ""
    case $REPLY in
        1) PROJECT_DIR="customer-support-agent" ;;
        2) PROJECT_DIR="financial-data-analyst" ;;
        3) PROJECT_DIR="computer-use-demo" ;;
        4) PROJECT_DIR="all" ;;
        *) print_error "Invalid selection"; exit 1 ;;
    esac
fi

# Function to create .env file for a project
create_env_file() {
    local dir=$1
    local env_file=""

    if [ -f "$dir/package.json" ]; then
        # Node.js project - use .env.local
        env_file="$dir/.env.local"
    elif [ -f "$dir/requirements.txt" ] || [ -f "$dir/computer_use_demo/requirements.txt" ]; then
        # Python project - use .env
        env_file="$dir/.env"
    fi

    if [ -n "$env_file" ]; then
        print_info "Creating $env_file"

        # Create or update .env file
        {
            echo "# Auto-generated by setup-devcontainer-oauth.sh"
            echo "# $(date)"
            echo ""
            echo "# Claude Code OAuth Token"
            echo "CLAUDE_CODE_OAUTH_TOKEN=$CLAUDE_CODE_OAUTH_TOKEN"
            echo ""
            if [ -n "$ANTHROPIC_API_KEY" ]; then
                echo "# Anthropic API Key"
                echo "ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY"
                echo ""
            fi

            # Add project-specific variables
            if [[ "$dir" == *"computer-use-demo"* ]]; then
                echo "# Computer Use Demo specific"
                echo "API_PROVIDER=anthropic"
                echo "WIDTH=1024"
                echo "HEIGHT=768"
                echo ""
            elif [[ "$dir" == *"customer-support-agent"* ]]; then
                echo "# Customer Support Agent specific (optional)"
                echo "# AWS_ACCESS_KEY_ID=your-aws-key"
                echo "# AWS_SECRET_ACCESS_KEY=your-aws-secret"
                echo "# AWS_SESSION_TOKEN=your-aws-token"
                echo ""
            fi
        } > "$env_file"

        print_success "Created $env_file"

        # Ensure it's in .gitignore
        local gitignore="$dir/.gitignore"
        if [ -f "$gitignore" ]; then
            if ! grep -q "$(basename "$env_file")" "$gitignore"; then
                echo "$(basename "$env_file")" >> "$gitignore"
                print_success "Added $(basename "$env_file") to .gitignore"
            fi
        fi
    fi
}

# Function to validate devcontainer setup
validate_devcontainer() {
    local dir=$1
    local devcontainer="$dir/.devcontainer/devcontainer.json"

    if [ -f "$devcontainer" ]; then
        print_success "Found devcontainer config: $devcontainer"

        # Check if CLAUDE_CODE_OAUTH_TOKEN is in remoteEnv
        if grep -q "CLAUDE_CODE_OAUTH_TOKEN" "$devcontainer"; then
            print_success "CLAUDE_CODE_OAUTH_TOKEN configured in devcontainer"
        else
            print_warning "CLAUDE_CODE_OAUTH_TOKEN not found in devcontainer config"
            print_info "You may need to update the devcontainer.json manually"
        fi
    else
        print_warning "No devcontainer config found at $devcontainer"
    fi
}

# Process projects
if [ "$PROJECT_DIR" = "all" ]; then
    print_info "Setting up all projects..."
    echo ""

    for dir in customer-support-agent financial-data-analyst computer-use-demo; do
        if [ -d "$dir" ]; then
            echo "Setting up: $dir"
            echo "-------------------"
            create_env_file "$dir"
            validate_devcontainer "$dir"
            echo ""
        fi
    done
else
    create_env_file "$PROJECT_DIR"
    validate_devcontainer "$PROJECT_DIR"
fi

echo ""
print_success "Setup complete!"
echo ""
echo "Next steps:"
echo "  1. Open the project in VS Code"
echo "  2. Click 'Reopen in Container' when prompted"
echo "  3. The Dev Container will automatically load your tokens"
echo ""
echo "Or use GitHub Codespaces:"
echo "  1. Add CLAUDE_CODE_OAUTH_TOKEN to GitHub Codespaces Secrets"
echo "  2. Add ANTHROPIC_API_KEY to GitHub Codespaces Secrets"
echo "  3. Create a new Codespace"
echo ""
print_info "For more details, see DEVCONTAINER_GUIDE.md"
